### PR TITLE
JQPlot work

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by yrodiere** [comment]
@gsmet Could you please tell me if this is still work in progress, or if it's ready to merge? Thanks.

**Comment by gsmet** [comment]
@fenrhil you can review it and merge it. Might just be a good idea to add more examples.

**Comment by yrodiere** [comment]
I think we're good, now. I also added some docs: https://github.com/openwide-java/owsi-core-parent/wiki/UI-Charts-and-plots

@julien-gonzalez , since you worked a lot with JQPlot, would you please take some time to review this (at least [the docs](https://github.com/openwide-java/owsi-core-parent/wiki/UI-Charts-and-plots)) and tell me if anything needs some polishing?

**Comment by julien-gonzalez** [comment]
@fenrhil, I've corrected a few typos in the doc (see [revisions comparison](https://github.com/openwide-java/owsi-core-parent/wiki/UI-Charts-and-plots/_compare/d52ab553ccd3a3043a2140cb354dbf4d9b91c587...9ad2b45d39d118db5c888e8e8d1cb98a67509c0e))
About the code itself, nothing shocked me. It's a good factorization for the majority of the use-cases we've met.

It could be relevant to detail or at least translate the short javadoc of `JQPlotAddDomReferenceResourceReference.java`. Basically jqPlot don't plot charts contained in a display:none element. So you have to manually replot chart if a former display:none element containing a chart become visible. The associated js set a jqPlot config option that allows to reference a chart, in order to call the ".replot()" function, when the element become visible.
We can talk about this (I can give you some concrete use-cases to work from), but there's nothing blocking the PR for me.

**Comment by yrodiere** [comment]
@julien-gonzalez I just added some documentation regarding the issue you were referring to: https://github.com/openwide-java/owsi-core-parent/wiki/UI-Charts-and-plots#the-plots-are-not-drawn
I took the liberty of adding a wicket Behavior addressing just this issue.

**Pull request merged**
